### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web-admin#2]
Viết hướng dẫn sử dụng trước khi dùng cho người sau.
Bao gôm:
- Clone từ github
- Tải dependecies
- Chạy development server
- Tạo Pull Request

**Note**: Có thể copy paste 1 số thứ từ các README.md khác của *Vietcode*.

**Comment by huonggiangbui** [comment]
=)) phong cách issue của footstep hả

**Comment by duc0905** [comment]
Phong cách của mọi nơi
Project nào cũng cần 1 cái README bắt mắt mà.

**Comment by huonggiangbui** [comment]
Cái label với project Todo cơ :)))

**Comment by tiuphun** [comment]
cái readme này có khác gì repo web ko anh 😑 

**ngoài thay npm bằng yarn**
