### ISSUE TITLE
Create custom theme

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web-admin#5]
Dùng [Material-UI Theme](https://material-ui.com/customization/theming/) để tạo custom pallete.

**Comment by duc0905** [comment]
Anh ngứa tay quá hihi

**Comment by huonggiangbui** [comment]
tự tạo issue tự assign....

**Comment by duc0905** [comment]
@huonggiangbui em thích thì đề xuất vài cái đi xong rùi làm
